// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CloseBrowser(arg1:string):Promise<void>;

export function CreateSession():Promise<main.Session>;

export function DeleteSession(arg1:string):Promise<void>;

export function GetSession(arg1:string):Promise<main.Session>;

export function GetSessions():Promise<Array<main.Session>>;

export function Greet(arg1:string):Promise<string>;

export function OpenBrowser(arg1:string,arg2:string):Promise<void>;

export function PassData():Promise<Array<string>>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;
