// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseBrowser(arg1) {
  return window['go']['main']['App']['CloseBrowser'](arg1);
}

export function CreateSession() {
  return window['go']['main']['App']['CreateSession']();
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function GetSession(arg1) {
  return window['go']['main']['App']['GetSession'](arg1);
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenBrowser(arg1, arg2) {
  return window['go']['main']['App']['OpenBrowser'](arg1, arg2);
}

export function PassData() {
  return window['go']['main']['App']['PassData']();
}

export function RenameSession(arg1, arg2) {
  return window['go']['main']['App']['RenameSession'](arg1, arg2);
}
