// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseBrowser():Promise<void>;

export function CloseSession():Promise<void>;

export function GotoTarget(arg1:string):Promise<void>;

export function OpenBrowser(arg1:string):Promise<void>;
