// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseBrowser() {
  return window['go']['main']['Session']['CloseBrowser']();
}

export function CloseSession() {
  return window['go']['main']['Session']['CloseSession']();
}

export function GotoTarget(arg1) {
  return window['go']['main']['Session']['GotoTarget'](arg1);
}

export function OpenBrowser(arg1) {
  return window['go']['main']['Session']['OpenBrowser'](arg1);
}
